### ISSUE TITLE
Enqueue trailingslashit

### ISSUE THREAD

**Issue by VivekManglani** [devgeniem/dustpress-js#1]
Should change this:

`wp_enqueue_script( 'dustpress',  plugin_dir_url( __FILE__ ) . '/js/dustpress-min.js', array('jquery'), '1.0.0', false );`

to:
`wp_enqueue_script( 'dustpress',  trailingslashit(plugin_dir_url( __FILE__ )) . 'js/dustpress-min.js', array('jquery'), '1.0.0', false );`

**Comment by Nomafin** [comment]
This was implemented in version 1.0.6.
